Repository ACCORD-NWP/AccordDaTools, pull requests merged in 2024-05, with the labels that each got.

#46 DFS calculation updated to include SGNSS. Plot script updated to plot…
  README.md
  scripts/plotdfs.py
  src/dfscomp.F90
Labels: enhancement

#47 Feature/move more doc
  README.md
  doc/make.jl
  doc/src/dfs.md
  doc/src/jbdiagnose.md
Labels: documentation

#48 Correct math markdown in DFS doc
  doc/src/dfs.md
Labels: bug, documentation

#49 Minor changes to documentation
  doc/src/diacov.md
  doc/src/index.md
Labels: documentation, enhancement

#50 dollars to ticks
  doc/src/dfs.md
Labels: bug, documentation

#52 Feature/merge diacov doc
  doc/src/diacov.md
  doc/tools/diacov.md
Labels: documentation, enhancement
