Repository ACCORD-NWP/AccordDaTools, pull requests merged in 2024-03, with the labels that each got.

#35 Update varbcdiagnose.sh again
  scripts/varbcdiagnose.sh
Labels: enhancement

#36 Add cv binary header listing program
  CMakeLists.txt
  doc/src/cvheaderlist.md
  scripts/CMakeLists.txt
  scripts/cv_header_list.sh
  src/cv_header_list.F90
  src/jbdiagnose.F90
Labels: enhancement

#38 Add link to cv header list
  doc/make.jl
Labels: bug

#40 Jcampinsp patch 3
  README.md
  doc/make.jl
  doc/src/varbccoeff.md
  scripts/CMakeLists.txt
  scripts/plotvarbccoeff.py
Labels: documentation, enhancement

#42 Add missing comma
  doc/make.jl
Labels: bug

#39 Domain properties automatic retrieval + try/except plotting correction
  README.md
  scripts/plotdiacov.py
  scripts/rundiacov.sh
Labels: enhancement

#43 Feature/move docs
  README.md
  doc/make.jl
  doc/src/dfs.md
  doc/src/diacov.md
  doc/src/varbccoeff.md
Labels: documentation
